"""preset.py"""

from .constants import *

default_world_settings = {
    WORLD_SETTINGS_SYNCHRONOUS_MODE: True,
    WORLD_SETTINGS_NO_RENDERING_MODE: False,
    WORLD_SETTINGS_FIXED_DELTA_SECONDS: 0.1,
    WORLD_SETTINGS_SUBSTEPPING: True,
    WORLD_SETTINGS_MAX_SUBSTEP_DELTA_TIME: 0.01,
    WORLD_SETTINGS_MAX_SUBSTEPS: 10,
    WORLD_SETTINGS_MAX_CULLING_DISTANCE: 0.0,
    WORLD_SETTINGS_DETERMINISTIC_RAGDOLLS: True,
    WORLD_SETTINGS_TILE_STREAM_DISTANCE: 80.0,
    WORLD_SETTINGS_ACTOR_ACTIVE_DISTANCE: 80.0,
}

default_tm_settings = {
    TM_SETTINGS_RANDOM_DEVICE_SEED: 3407,
    TM_SETTINGS_HYBRID_PHYSICS_MODE: True,
    TM_SETTINGS_HYBRID_PHYSICS_RADIUS: 80.0,
    TM_SETTINGS_GLOBAL_DISTANCE_TO_LEADING_VEHICLE: 10.0,
    TM_SETTINGS_GLOBAL_PERCENTAGE_SPEED_DIFFERENCE: 10.0,
    TM_SETTINGS_SYNCHRONOUS_MODE: True,
    TM_SETTINGS_RESPAWN_DORMANT_VEHICLES: True,
}

default_rgb_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.camera.rgb",
        SENSOR_DEFINITIONS_COMMON_ID: "front",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_RGB_IMAGE_SIZE_X: 768,
        SENSOR_DEFINITIONS_CONFIG_RGB_IMAGE_SIZE_Y: 384,
        SENSOR_DEFINITIONS_CONFIG_RGB_FOV: 90.0,
        SENSOR_DEFINITIONS_CONFIG_RGB_GAMMA: 2.2,
        SENSOR_DEFINITIONS_CONFIG_RGB_SHUTTER_SPEED: 100.0,
        SENSOR_DEFINITIONS_CONFIG_RGB_ISO: 100.0,
        SENSOR_DEFINITIONS_CONFIG_RGB_FSTOP: 8.0,
        SENSOR_DEFINITIONS_CONFIG_RGB_TEMP: 6500.0,
        SENSOR_DEFINITIONS_CONFIG_RGB_ENABLE_POSTPROCESS_EFFECTS: True,
    }
}

default_of_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.camera.optical_flow",
        SENSOR_DEFINITIONS_COMMON_ID: "front",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_OPTICAL_FLOW_IMAGE_SIZE_X: 768,
        SENSOR_DEFINITIONS_CONFIG_OPTICAL_FLOW_IMAGE_SIZE_Y: 384,
        SENSOR_DEFINITIONS_CONFIG_OPTICAL_FLOW_FOV: 90.0,
    }
}

default_depth_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.camera.depth",
        SENSOR_DEFINITIONS_COMMON_ID: "front",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_DEPTH_IMAGE_SIZE_X: 768,
        SENSOR_DEFINITIONS_CONFIG_DEPTH_IMAGE_SIZE_Y: 384,
        SENSOR_DEFINITIONS_CONFIG_DEPTH_FOV: 90.0,
    }
}

default_semantic_segmentation_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.camera.semantic_segmentation",
        SENSOR_DEFINITIONS_COMMON_ID: "front",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_SEMANTIC_SEGMENTATION_IMAGE_SIZE_X: 768,
        SENSOR_DEFINITIONS_CONFIG_SEMANTIC_SEGMENTATION_IMAGE_SIZE_Y: 384,
        SENSOR_DEFINITIONS_CONFIG_SEMANTIC_SEGMENTATION_FOV: 90.0,
    }
}

default_lidar_ray_cast_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.lidar.ray_cast",
        SENSOR_DEFINITIONS_COMMON_ID: "lidar",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_CHANNELS: 16,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_RANGE: 80.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_POINTS_PER_SECOND: 60000,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_ROTATION_FREQUENCY: 10.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_UPPER_FOV: 15.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_LOWER_FOV: -15.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_DROPOFF_GENERAL_RATE: 0.5,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_DROPOFF_INTENSITY_LIMIT: 0.8,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_NOISE_STDDEV: 0.1
    }
}

default_lidar_ray_cast_semantic_front_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.lidar.ray_cast_semantic",
        SENSOR_DEFINITIONS_COMMON_ID: "lidar",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_CHANNELS: 16,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_RANGE: 80.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_POINTS_PER_SECOND: 60000,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_ROTATION_FREQUENCY: 10.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_UPPER_FOV: 15.0,
        SENSOR_DEFINITIONS_CONFIG_LIDAR_RAY_CAST_SEMANTIC_LOWER_FOV: -15.0,
    }
}

default_gnss_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.other.gnss",
        SENSOR_DEFINITIONS_COMMON_ID: "other",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_SEED: 3407,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_ALT_BIAS: 0.0,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_ALT_STDDEV: 0.0,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_LAT_BIAS: 0.0,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_LAT_STDDEV: 0.0,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_LON_BIAS: 0.0,
        SENSOR_DEFINITIONS_CONFIG_GNSS_NOISE_LON_STDDEV: 0.0,
    }
}

default_imu_sensor_definition = {
    SENSOR_DEFINITIONS_COMMON: {
        SENSOR_DEFINITIONS_COMMON_TYPE: "sensor.other.imu",
        SENSOR_DEFINITIONS_COMMON_ID: "other",
    },
    SENSOR_DEFINITIONS_TRANSFORM: {
        SENSOR_DEFINITIONS_TRANSFORM_X: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_Y: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_Z: 2.0,
        SENSOR_DEFINITIONS_TRANSFORM_ROLL: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_PITCH: 0.0,
        SENSOR_DEFINITIONS_TRANSFORM_YAW: 0.0,
    },
    SENSOR_DEFINITIONS_CONFIG: {
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_SEED: 3407,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_ACCEL_STDDEV_X: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_ACCEL_STDDEV_Y: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_ACCEL_STDDEV_Z: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_BIAS_X: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_BIAS_Y: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_BIAS_Z: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_STDDEV_X: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_STDDEV_Y: 0.0,
        SENSOR_DEFINITIONS_CONFIG_IMU_NOISE_GYRO_STDDEV_Z: 0.0,
    }
}
